version: "3"
services:

  postgres:
    image: zerrtech/postgres:latest
    ports:
      - "5432"
    networks:
      - backend

  spacewalk:
    build:
      context: .
      dockerfile: Dockerfile
    image: spacewalk
    stdin_open: true
    tty: true
    links:
      - postgres
    networks:
      - backend

networks:
  backend:
